### PR TITLE
A small bugfix

### PR DESCRIPTION
**Pull request by scoopex**
Overlooked a unseeded parenthesis. Sorry.
A new release would be a good thing :-)

### CODE REVIEW

**Review by dploeger — APPROVED** [review]
Woops. Oversaw them as well. Thanks! 🎁

**Comment by scoopex** [comment]
@dploeger can you publish the 4.0.2 release to puppetforge?

**Comment by dploeger** [comment]
Oh, sorry. I thought we had workflows here that took care of it. Apparently this repo wasn't converted from travis yet. I'll take a look into it!

**Comment by dploeger** [comment]
It's deployed now

**Pull request merged**
