### PR TITLE
Close #7: puppet 8 compatibility

### LINKED ISSUE #7: Downloading of artifacts failes with puppet8
With puppet 8, the following expressions fails:

```
    $k9s_file="k9s_Linux_amd64.tar.gz"
      githubreleases_download { "/tmp/${k9s_file}":
        author            => 'derailed',
        repository        => 'k9s',
        asset             => true,
          asset_filepattern => "${k9s_file}",
      }
```

The error ouput:
```
Error: Could not set 'present' on ensure: uninitialized constant PSON (file: /etc/puppetlabs/pxp-agent/modules/ubuntudesktop/manifests/aspect/software.pp, line: 392)
Error: Could not set 'present' on ensure: uninitialized constant PSON (file: /etc/puppetlabs/pxp-agent/modules/ubuntudesktop/manifests/aspect/software.pp, line: 392)
Wrapped exception:
uninitialized constant PSON
Error: /Stage[main]/Ubuntudesktop::Aspect::Software/Githubreleases_download[/tmp/k9s_Linux_amd64.tar.gz]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: uninitialized constant PSON (file: /etc/puppetlabs/pxp-agent/modules/ubuntudesktop/manifests/aspect/software.pp, line: 392)
```

### PR DESCRIPTION
**Pull request by scoopex**

### CODE REVIEW

**Comment by dploeger** [comment]
@scoopex  I'm sorry, can you kindly now please reword the commit to something like:

```
feat: Fixed Puppet 8 compatibility
fixes #7 
```

You can use `git rebase main -i` for that in case you don't know.

Thanks a lot!

**Comment by scoopex** [comment]
Yes, i know that :-) Done :-)

**Comment by dploeger** [comment]
Awesome. Thanks a lot! 🎁

**Comment by dploeger** [comment]
Released as 4.1.0

**Pull request merged**
